name: CD
author: Vladimir Ovsyukov <vovansuper@mail.ru>

on:
  push:
    branches: 
      - master
      - releases
      - test

jobs:
  build_and_fbdeploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies (lacal and global)
      run: |
        npm ci
        npm install --global @ionic/cli@latest firebase-tools@latest
    
    - name: Build Project in prod mode
      run: npm run build:prod --if-present
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build_artifact
        path: www
    
    - name: Publish to Firebase hosting
      env: 
        FIREBASE_TOKEN: ${{ secrets.FB_SECRET }}
      run: npx firebase deploy --only hosting --project al-flashcard-proj --token "$FIREBASE_TOKEN"
