# A basic CI script to automate building / testing AL-flashcard app

name: CI

# Trigger on master push / pull requests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install packages global
      run: echo Installing..!
      
    - run: npm install -g @ionic/cli > /dev/null
    - run: npm install -g @angular/cli > /dev/null
    - run: npm ci
    - run: npm run build

    - name: Run tests
      run: |
        echo Running tests,
    - run: npm test -- --configuration=ci
